# Generated by Django 3.1.6 on 2021-02-06 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('apelido', models.CharField(max_length=30, unique=True)),
                ('cargo', models.IntegerField(blank=True, null=True)),
                ('ctps', models.CharField(max_length=30, unique=True)),
                ('dtadmisao', models.DateTimeField(db_column='dtAdmisao')),
                ('imagem', models.TextField(blank=True, null=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=19)),
                ('situacao', models.TextField()),
            ],
            options={
                'db_table': 'colaborador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigSituacaoCadastro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'config_situacao_cadastro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                (
                'classificacaojuridica', models.IntegerField(blank=True, db_column='classificacaoJuridica', null=True)),
                ('cnpj', models.CharField(max_length=14)),
                ('ie', models.CharField(blank=True, max_length=14, null=True)),
                ('razao', models.CharField(max_length=120)),
                ('fantasia', models.CharField(max_length=80)),
                ('cliente', models.TextField()),
                ('fornecedor', models.TextField()),
                ('transportadora', models.TextField()),
                ('datacadastro', models.DateTimeField(db_column='dataCadastro')),
                ('dataatualizacao', models.DateTimeField(blank=True, db_column='dataAtualizacao', null=True)),
                ('inscricaosuframa',
                 models.CharField(blank=True, db_column='inscricaoSuframa', max_length=9, null=True)),
                ('inscricaomunicipal',
                 models.CharField(blank=True, db_column='inscricaoMunicipal', max_length=15, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=1500, null=True)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=19)),
                ('prazopadrao', models.IntegerField(db_column='prazoPadrao')),
                ('diautilprazo', models.TextField(db_column='diaUtilPrazo')),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaEndereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'empresa_endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('complemento', models.CharField(blank=True, max_length=80, null=True)),
                ('enderecotipo', models.IntegerField(blank=True, db_column='enderecoTipo', null=True)),
                ('logradouro', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuPrincipal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('icomenu', models.CharField(blank=True, db_column='icoMenu', max_length=120, null=True)),
                ('menu', models.CharField(max_length=45)),
                ('menulabel', models.CharField(db_column='menuLabel', max_length=45)),
                ('menupai_id', models.IntegerField(db_column='menuPai_id')),
                ('tabpane', models.TextField(db_column='tabPane')),
                ('teclaatalho', models.CharField(blank=True, db_column='teclaAtalho', max_length=45, null=True)),
            ],
            options={
                'db_table': 'menu_principal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('capital', models.TextField()),
                ('ddd', models.CharField(max_length=2)),
                ('descricao', models.CharField(max_length=80)),
                ('ibge_codigo', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=11)),
                ('principal', models.TextField()),
            ],
            options={
                'db_table': 'telefone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelefoneOperadora',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
                ('webservice_id', models.CharField(blank=True, db_column='webService_id', max_length=5, null=True)),
            ],
            options={
                'db_table': 'telefone_operadora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'uf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=128)),
                ('id',
                 models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True,
                                      serialize=False, to='cafeperfeito.colaborador')),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
